name: Node Build+Deploy

on: push

jobs:
  restart-aws:
    name: Restart AWS ECS Task
    runs-on: ubuntu-latest
    steps:
      - 
        name: AWS Login
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsFamily: marjorie
        run: |
          isTaskRunning=$(aws --output text ecs list-tasks --cluster JKU_ASG_Cluster --family ${awsFamily})
          echo "isTaskRunning? --${isTaskRunning}--"
          if [ ! -z "$isTaskRunning" ]; then
            taskId=$(echo "${isTaskRunning}" | cut -f2)
            echo "taskId--${taskId}--"
            aws --output text ecs stop-task --cluster JKU_ASG_Cluster --task ${taskId}
          fi
          aws --output text ecs run-task --cluster JKU_ASG_Cluster --task-definition ${awsFamily} --started-by GithubAction