name: Build & Deploy Docker Image

env:
  PROJECT_NAME: marjorie

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set Debug Mode to False
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "debug=True"
          replace: "debug=False"
          regex: false
      - name: Git config
        run: |
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/
          git config --add --global url."https://github.com/".insteadOf git@github.com:
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/jku-vds-lab/${{ env.PROJECT_NAME  }}
      - name: Print metadata
        run: |
          echo ${{ steps.meta.outputs.tags }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  restart-aws:
    name: Restart AWS ECS Task
    runs-on: ubuntu-latest
    needs: [build]
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Check if Task is Running and Stop it 
        run: |
          isTaskRunning=$(aws --output text ecs list-tasks --cluster JKU_ASG_Cluster --family ${PROJECT_NAME})
          if [ ! -z "$isTaskRunning" ]; then
            echo "TASK IS RUNNING "
            taskId=$(echo "${isTaskRunning}" | cut -f2)
            echo "STOPPING TASK with taskId: ${taskId}"
            aws --output text ecs stop-task --cluster JKU_ASG_Cluster --task ${taskId}
          else
            echo "TASK STOPPED"
          fi
      - name: Start Task
        run: |
          aws --output text ecs run-task --cluster JKU_ASG_Cluster --task-definition ${PROJECT_NAME} --started-by GithubAction
