name: Node Build+Deploy

on: push

jobs:
  restart-aws:
    name: Restart AWS ECS Task
    runs-on: ubuntu-latest
    steps:
      - 
        name: AWS Configure
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "$AWS_DEFAULT_REGION"
          aws configure
